### ISSUE TITLE
A kind request from the BxDecay0 team

### ISSUE THREAD

**Issue by fmauger** [LArSoft/larsim#45]
Hi LArSofters,

Not really an issue but a kind request...
Would you agree if I put a reference to Dune and its LArSoft on the BxDecay0 main page ?
I plan to list a few projects (with logos) that use this lib within their MC tools. 
Many thanks to welcome my request with good will. ;-)
Regards
frc

**Comment by erica-snider** [comment]
Hi!
     My apologies. This seems to have slipped our attention as it came in via a route that we do not normally use.

I can't speak for DUNE offline, but LArSoft is public code, so feel free to reference LArSoft.org, the LArSoft GitHub organization and repositories, or the LArSoft wiki on the BxDecay0 page. 

Erica

**Comment by fmauger** [comment]
Thanks Erica. Simply referencing LArSoft is fine for me. I close this issue. There is no need to move my request to a specific experiment.
